### ISSUE TITLE
merge applied_* metric and proposed_* metric

### ISSUE THREAD

**Issue by sanposhiho** [mercari/tortoise#248]
We can merge them by introducing a new tag named `update_mode`.

**Comment by harpratap** [comment]
It wouldn't make a difference I think. If there are 10 namespaces with 10 Tortoise for 10 HPA with 2 containers each
applied_xx metric cardinality would be = 10 * 10 * 10 * 2 = 2000
proposed_xx metric cardinality would be = 10 * 10 * 10 * 2 = 2000
Total cardinality = 2000 + 2000 = 4000

If we add another tag instead then 
xx metric cardinality would be = 10 * 10 * 10 * 2 *2 = 4000

**Comment by sanposhiho** [comment]
Yes, you're right 😓 Let's just close it since no worth enough to break existing metrics.
