### ISSUE TITLE
Make the annotation naming consistent

### ISSUE THREAD

**Issue by sanposhiho** [mercari/tortoise#322]
## Problem

This issue is raised at https://github.com/mercari/tortoise/pull/308.

https://github.com/mercari/tortoise/blob/main/pkg/annotation/annotation.go

We have annotations starting from `tortoises.autoscaling.mercari.com/` and from `tortoise.autoscaling.mercari.com/`. We should unify it with `tortoise.autoscaling.mercari.com/*` ideally.

## Proposal

So, basically what we have to do is rename `"tortoises.autoscaling.mercari.com/tortoise-name"` to `"tortoise.autoscaling.mercari.com/tortoise-name"`.

But, it cannot be done simply because if we just rename the annotation, it'd break existing tortoises working in the cluster.

We have to migrate the annotation gradually. 

**First step**
- We create a new annotation `"tortoise.autoscaling.mercari.com/tortoise-name"`. HPAs for new tortoises will get this annotation instead of the old one. 
- But also keep the old one `"tortoises.autoscaling.mercari.com/tortoise-name"`. We mark `"tortoises.autoscaling.mercari.com/tortoise-name"` (old one) as deprecated.
- If HPA doesn't have `"tortoise.autoscaling.mercari.com/tortoise-name"`, we try to look at `"tortoises.autoscaling.mercari.com/tortoise-name"`.
- [When we update HPA](https://github.com/mercari/tortoise/blob/0ee23a337dbb83c1eb24e6df20ef23207c484059/pkg/hpa/service.go#L613-L657), we change the annotation's key from the old one to the new one. So, if users deploy a new version, their tortoises' HPAs should be migrated from the old annotation to the new annotation.

**Second step**

It should be done enough time passed after the first step.
- Remove the old annotation from the code. It's definitely a breaking change though, we guide people not to upgrade with a big jump - let them do step by step, so that their tortoises are migrated correctly.

**Comment by sadath-12** [comment]
Hi @sanposhiho as this is not production ready can we just change it ?

**Comment by sanposhiho** [comment]
No. It's mentioned it as "not production ready" for now though, actually in order to evaluate tortoise's recommendation logic in real world, our company already started to use it in the dev cluster widely and even some workloads in prod. Also, either way, regardless of our company, given it's open-source, we should try not to bring any breaking changes as much as possible.

So, I do believe we have to follow the gradual migration of the annotation, like the way I proposed at the top.

**Comment by sadath-12** [comment]
thanks for clearing . will work on it 😊

**Comment by sanposhiho** [comment]
https://github.com/mercari/tortoise/pull/359 removed the tortoise name annotation itself. Closing this.
